service: wpa-user-saas

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: usersTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:237071355172:table/usersTable"

functions:
  getUser:
    handler: bootstrap
    events:
      - http:
          path: /user/{phone}
          method: GET

  createUser:
    handler: bootstrap
    events:
      - http:
          path: /user
          method: POST


plugins:
  - serverless-step-functions

